return {
    "nvim-treesitter/nvim-treesitter",

    opts = {
        ensure_installed = {
            "bash",
            "c",
            "cpp",
            "css",
            "git_config",
            "gitcommit",
            "gitignore",
            "glsl",
            "html",
            "kdl",
            "json",
            "java",
            "javascript",
            "julia",
            "latex",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "norg",
            "org",
            "python",
            "query",
            "r",
            "regex",
            "tsx",
            "typescript",
            "vim",
            "vimdoc",
            "yaml",
        },
    },
}
